# registry.cn-hangzhou.aliyuncs.com/silverbulllet/knative-serving-activator:v0.14.0
FROM gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:3b530bbcf892aff098444ae529a9d4150dfd0cd35c97babebd90eedae34ad8af

MAINTAINER silverbulllet <silverbulllet@163.com>