# registry.cn-hangzhou.aliyuncs.com/silverbulllet/knative-net-istio-webhook:v0.14.0
FROM gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:b04b047b1c980191bcfb046b97ab0afd39e19e570be341ce0028483fc548aa22

MAINTAINER silverbulllet <silverbulllet@163.com>