# registry.cn-hangzhou.aliyuncs.com/silverbulllet/knative-serving-controller:v0.14.0
FROM gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:71f7c9f101e7e30e82a86d203fb98d6fa607c8d6ac2fcb73fd1defd365795223

MAINTAINER silverbulllet <silverbulllet@163.com>