# registry.cn-hangzhou.aliyuncs.com/silverbulllet/tekton-pipeline-webhook:v0.12.0
FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.12.0@sha256:f183f19b46375111a928d92dcf28d09f60beeb3dc0be889f3465592eb52873c4

MAINTAINER silverbulllet <silverbulllet@163.com>