# registry.cn-hangzhou.aliyuncs.com/silverbulllet/tekton-pipeline-controller:v0.12.0
FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.12.0@sha256:70c85c0e8201cb8c90908fbc4ac5b9fe05cc6d85744aaf647d58bd059c5c4344


MAINTAINER silverbulllet <silverbulllet@163.com>