# registry.cn-hangzhou.aliyuncs.com/silverbulllet/knative-serving-queue:v0.14.0
FROM gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:f32c20456c6349a4fe99c83060009c7e9f6ba0c644ef854a04514e1f8aca982e

MAINTAINER silverbulllet <silverbulllet@163.com>