# registry.cn-hangzhou.aliyuncs.com/silverbulllet/knative-net-istio-controller:v0.14.0
FROM gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:d31c49a1f07584f0393d651b4f9befb845e64e6b55c9d244e046f309560b6d0e

MAINTAINER silverbulllet <silverbulllet@163.com>